// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCavlqR88dcj_nmZhqJmRIRNdem0rhFFRI',
    appId: '1:551850608952:web:aa5a50c1768eed537bd9cd',
    messagingSenderId: '551850608952',
    projectId: 'recording-extension',
    authDomain: 'recording-extension.firebaseapp.com',
    storageBucket: 'recording-extension.firebasestorage.app',
    measurementId: 'G-0MCE3MLDEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpTwgPfpGIZFiPt8PodwYCRYIpm14TbyM',
    appId: '1:551850608952:android:9af2eb3cfc0f32e67bd9cd',
    messagingSenderId: '551850608952',
    projectId: 'recording-extension',
    storageBucket: 'recording-extension.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD4JzzYMACBr5SAamdw9FyHnWEcLh22-Q',
    appId: '1:551850608952:ios:d33c110fe8155f437bd9cd',
    messagingSenderId: '551850608952',
    projectId: 'recording-extension',
    storageBucket: 'recording-extension.firebasestorage.app',
    iosBundleId: 'com.example.screenRecording',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCD4JzzYMACBr5SAamdw9FyHnWEcLh22-Q',
    appId: '1:551850608952:ios:d33c110fe8155f437bd9cd',
    messagingSenderId: '551850608952',
    projectId: 'recording-extension',
    storageBucket: 'recording-extension.firebasestorage.app',
    iosBundleId: 'com.example.screenRecording',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCavlqR88dcj_nmZhqJmRIRNdem0rhFFRI',
    appId: '1:551850608952:web:c499f224a20f44be7bd9cd',
    messagingSenderId: '551850608952',
    projectId: 'recording-extension',
    authDomain: 'recording-extension.firebaseapp.com',
    storageBucket: 'recording-extension.firebasestorage.app',
    measurementId: 'G-H0XYN172FZ',
  );

}